% $Header: /var/cvs/mbdyn/mbdyn/mbdyn-1.0/tests/rbk/tm4760/tm4760.m,v 1.2 2008/12/31 09:37:28 masarati Exp $
%
% NASA Technical Memorandum 4760
% ARL Technical Report 1389
%
% Rotating Shake Test and Modal Analysis of a Model Helicopter Rotor Blade
% W. Keats Wilkie, Paul H. Mirick, and Chester W. Langston
% Vehicle Technology Center
% U.S. Army Research Laboratory
% Langley Research Center Hampton, Virginia
%
% Table 1. Properties of Model Rotor Blade
% (a) Structural    properties
%
%                                                                                      Section mass  Center of mass
% Inboard                 Chordwise area  Flapwise area  Torsional area                moment        offset forward
% sec. radius, Sec. spar  moment of       moment of      moment of       Section mass, of inertia,   of elastic axis,
% in.          area, in^2 inertia, in^4   inertia, in^4  inertia, in^4   lb/in.        lb-in^2/in.   in.
table_1_a = [...
 3.00          5.50       0.5000          0.5000         0.2632          0.4251        0.2200         0.0           ;
 6.87          0.371      0.1500          0.0500         0.1316          0.1938        0.04826        0.0           ;
 8.87          0.371      0.0250          0.0040         0.0105          0.04086       0.02505        0.0           ;
10.625         0.371      0.0250          0.0040         0.0105          0.15113       0.05671        0.0           ;
12.50          0.377      0.0355          0.00394        0.0394          0.14048       0.05559        0.0           ;
13.00          0.386      0.0252          0.00249        0.00976         0.03134       0.02779        0.0           ;
15.375         0.339      0.0252          0.00249        0.00976         0.04376       0.02961        0.0           ;
17.85          0.278      0.03040         0.00231        0.00674         0.04123       0.02888        0.0           ;
23.75          0.249      0.02636         0.00181        0.00565         0.0400        0.02810        0.0           ;
28.25          0.224      0.02447         0.00151        0.00485         0.03903       0.02756        0.0           ;
51.00          0.247      0.02447         0.00151        0.00485         0.03903       0.02756        0.0           ;
52.75          0.279      0.02448         0.00160        0.00502         0.04125       0.02826        0.0           ;
53.00          0.305      0.0500          0.00500        0.01435         0.07867       0.03984       -0.106         ;
54.00          0.099      0.0400          0.00400        0.01148         0.0607        0.03563       -0.170         ;
54.25          0.05       0.0050          0.00050        0.01435         0.01101       0.004401      -0.940         ];

%
% (b) Assumed material properties
% Modulus of elasticity, lb/in^2  Poisson's ratio
% 1.0 x 10^7                      0.3
E = 1.e+7;
nu = 0.3;

C_RADIUS = 1;
C_AREA = 2;
C_JCHORD = 3;
C_JBEAM = 4;
C_JTORS = 5;
C_MASS = 6;
C_JPOLAR = 7;
C_YCM = 8;

nbeam = 5;
nnode = 2*nbeam + 1;

x_cutout = table_1_a(2, C_RADIUS);
x_radius = table_1_a(end, C_RADIUS);

x_nodes = x_cutout + (x_radius - x_cutout)*[0:nnode - 1]'/(nnode - 1);
dx_nodes = x_nodes(2) - x_nodes(1);
x_epoints(1:2:2*nbeam, 1) = x_nodes(2:2:end) - 1/sqrt(3)*dx_nodes;
x_epoints(2:2:2*nbeam, 1) = x_nodes(2:2:end) + 1/sqrt(3)*dx_nodes;

% nodes
fd = fopen('tm4760_blade.nod', 'w');

fprintf(fd, '# $Header: /var/cvs/mbdyn/mbdyn/mbdyn-1.0/tests/rbk/tm4760/tm4760.m,v 1.2 2008/12/31 09:37:28 masarati Exp $\n');
fprintf(fd, '#\n');
fprintf(fd, '# Rotor blade model for MBDyn > 1.3.4\n');
fprintf(fd, '# Author: Pierangelo Masarati <masarati@aero.polimi.it>\n');
fprintf(fd, '# Data from:\n');
fprintf(fd, '#\n');
fprintf(fd, '# NASA Technical Memorandum 4760\n');
fprintf(fd, '# ARL Technical Report 1389\n');
fprintf(fd, '#\n');
fprintf(fd, '# Rotating Shake Test and Modal Analysis of a Model Helicopter Rotor Blade\n');
fprintf(fd, '# W. Keats Wilkie, Paul H. Mirick, and Chester W. Langston\n');
fprintf(fd, '# Vehicle Technology Center\n');
fprintf(fd, '# U.S. Army Research Laboratory\n');
fprintf(fd, '# Langley Research Center Hampton, Virginia\n');
fprintf(fd, '#\n');
fprintf(fd, '# file generated by ''tm4760.m'' - modifications could be overwritten\n');
fprintf(fd, '# rotor blade nodes for MBDyn > 1.3.4\n');

for n = 1:nnode,
	fprintf(fd, '\n');
	fprintf(fd, 'structural: CURR_BLADE + %d, dynamic,\n', n - 1);
	fprintf(fd, '\tposition, reference, CURR_BLADE, %+17.10e, %+17.10e, %+17.10e,\n', x_nodes(n), 0., 0.);
	fprintf(fd, '\torientation, reference, CURR_BLADE, eye,\n');
	fprintf(fd, '\tvelocity, reference, CURR_BLADE, null,\n');
	fprintf(fd, '\tangular velocity, reference, CURR_BLADE, null;\n');
end

fclose(fd);

% nodes
fd = fopen('tm4760_blade.elm', 'w');

fprintf(fd, '# $Header: /var/cvs/mbdyn/mbdyn/mbdyn-1.0/tests/rbk/tm4760/tm4760.m,v 1.2 2008/12/31 09:37:28 masarati Exp $\n');
fprintf(fd, '#\n');
fprintf(fd, '# Rotor blade model for MBDyn > 1.3.4\n');
fprintf(fd, '# Author: Pierangelo Masarati <masarati@aero.polimi.it>\n');
fprintf(fd, '# Data from:\n');
fprintf(fd, '#\n');
fprintf(fd, '# NASA Technical Memorandum 4760\n');
fprintf(fd, '# ARL Technical Report 1389\n');
fprintf(fd, '#\n');
fprintf(fd, '# Rotating Shake Test and Modal Analysis of a Model Helicopter Rotor Blade\n');
fprintf(fd, '# W. Keats Wilkie, Paul H. Mirick, and Chester W. Langston\n');
fprintf(fd, '# Vehicle Technology Center\n');
fprintf(fd, '# U.S. Army Research Laboratory\n');
fprintf(fd, '# Langley Research Center Hampton, Virginia\n');
fprintf(fd, '#\n');
fprintf(fd, '# file generated by ''tm4760.m'' - modifications could be overwritten\n');
fprintf(fd, '# rotor blade elements for MBDyn > 1.3.4\n');

for b = 1:nnode,
	fprintf(fd, '\n');
	fprintf(fd, 'body: CURR_BLADE + %d, CURR_BLADE + %d,\n', b - 1, b - 1);

	if (b == 1),
		idx_i = 1;
	else
		idx_i = idx_f;
	end

	if (b == nnode),
	end
end

fclose(fd);
